/*
Created: 11/7/2015
Modified: 11/7/2015
Model: CTG Data2 Senion Engineering Prove Your Craft
Company: Intuit, Inc.
Version: 1.0.0
Database: HP Vertica
*/

----------------------------------CAVEOTS FOR PYC-------------------------------

-- * I would normally put STG and NON-STG tables in different schemas to reduce
--   confusion for the customers of the data model. Given that I only have one
--	 schema to work with they are in the same schema.


--------------------------------------------------------------------------------


-----------------------------STAGE TABLE DEFINITIONS-----------------------------


--STG_FACT_CLICKSTREAM THAT WILL BE THE TABLE .CSV RECORDS ARE COPIED INTO
CREATE TABLE PYC.STG_FACT_CLICKSTREAM
(
TRANS_ID BIGINT NOT NULL,
VISITOR_ID BIGINT NOT NULL,
SCREEN_ID BIGINT NOT NULL,
HIT_TIMESTAMP TIMESTAMP NOT NULL,
CONSTRAINT PK_STG_FACT_CLICKSTREAM PRIMARY KEY (TRANS_ID)
)
ORDER BY TRANS_ID
SEGMENTED BY HASH(TRANS_ID) ALL NODES
;


--STG_FACT_AUTH THAT WILL BE THE TABLE AUTHS ARE PUT INTO FROM REST
CREATE TABLE PYC.STG_FACT_AUTH
(
AUTH_ID BIGINT NOT NULL,
LOGINTIME TIMESTAMP NOT NULL,
VISITOR_ID BIGINT NOT NULL,
CONSTRAINT PK_STG_FACT_AUTH PRIMARY KEY (AUTH_ID)
)
--TODO: TEST ORDERING ON AUTH_ID VS VISITOR_ID (POTENTAILLY BOTH)
ORDER BY AUTH_ID
SEGMENTED BY HASH(AUTH_ID) ALL NODES
;


--------------------------------------------------------------------------------


----------------------------FACT TABLE DEFINITIONS------------------------------


--FACT_CLICKSTREAM TABLE THAT WILL HOLD ALL OF THE CLICKSTREAM RECORDS
CREATE TABLE PYC.FACT_CLICKSTREAM
(
TRANS_ID BIGINT NOT NULL,
VISITOR_ID BIGINT NOT NULL,
SCREEN_ID BIGINT NOT NULL,
HIT_TIMESTAMP BIGINT NOT NULL,
CREATED_TIMESTAMP TIMESTAMP DEFAULT STATEMENT_TIMESTAMP() NOT NULL,
UPDATED_TIMESTAMP TIMESTAMP NULL,
CONSTRAINT PK_FACT_CLICKSTREAM PRIMARY KEY (TRANS_ID)
)
--TODO: EXPERIMENT WITH ORDERING BY TRANS_ID, POTENTAILLY CREATE A PROJECTION
ORDER BY VISITOR_ID, SCREEN_ID
--TODO: EXPERIMENT WITH SEGMENTATION IN SINGLE NODE ENV'S
SEGMENTED BY HASH(TRANS_ID) ALL NODES
--PARTITIONING HERE WOULD BE NECESSARY FOR A PRODUCTION ENVIRONMENT GIVEN THE
--LARGE SIZE OF CLICKSTREAM DATA BUT IS UNECESSARY FOR A SINGLE NODE ENV
;


--FACT_AUTH THAT WILL BE THE SOURCE OF TRUTH FOR ALL AUTHS
CREATE TABLE PYC.FACT_AUTH
(
AUTH_ID BIGINT NOT NULL,
LOGINTIME TIMESTAMP NOT NULL,
VISITOR_ID BIGINT NOT NULL,
CREATED_TIMESTAMP TIMESTAMP DEFAULT STATEMENT_TIMESTAMP() NOT NULL,
UPDATED_TIMESTAMP TIMESTAMP NULL,
CONSTRAINT PK_FACT_AUTH PRIMARY KEY (AUTH_ID)
)
ORDER BY AUTH_ID
SEGMENTED BY HASH(AUTH_ID) ALL NODES
;


--------------------------------------------------------------------------------


----------------------------AGG TABLE DEFINITIONS-------------------------------


--AGG_SESSION THAT WILL HOLD THE SESSIONIZED POST-PROCESSED DATA
CREATE TABLE PYC.AGG_SESSION
(
VISITOR_ID BIGINT NOT NULL,
VISIT_NUM BIGINT NOT NULL,
AUTH_ID BIGINT NULL,
SCREEN_ID BIGINT NOT NULL,
TIMESTAMP TIMESTAMP NOT NULL,
CREATED_TIMESTAMP TIMESTAMP DEFAULT STATEMENT_TIMESTAMP() NOT NULL,
UPDATED_TIMESTAMP TIMESTAMP NULL,
CONSTRAINT PK_AGG_SESSION PRIMARY KEY (VISITOR_ID)
)
ORDER BY VISITOR_ID, VISIT_NUM
SEGMENTED BY HASH(VISITOR_ID) ALL NODES
;


--------------------------------------------------------------------------------


----------------------------FOREIGN KEY DEFINITIONS-----------------------------


--------------------------------------------------------------------------------
